<template>
  <cq-layout-section>
    <h1 class="text-h3 pb-10">{{ t(`title.${personType}`)}}</h1>
    <cq-blocks-sections-paragraphWithImage
      :text="t(`description.${personType}`)"
      image="https://dummyimage.com/80/8d5b4c/ffffff"
    />
  </cq-layout-section>
</template>
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

interface Props {
  personType: string | string []
}

defineProps<Props>()

const { t } = useI18n({ useScope: 'local', inheritLocale: true })
</script>
<i18n>
{
  "es": {
    "title": {
      "adolescent": "Adolescentes",
      "kids": "Bebes / Niños",
      "elder": "Personas mayores",
      "pregnant": "Embarazadas",
      "workers": "Trabajadores",
      "sport": "Deportistas"
    },
    "description": {
      "adolescent": "Durante todo el largo de su nacimiento, el bebe pasara por momentos muy estresantes ; de su bajada en el canal vaginal de su madre a su salida entera en un entorno externo extraño.<br><br>A lo largo de su bajada, puede ser que el bebe se queda bloqueada en una posicion o que enceuntra obstaculos que le impide esfuerzos para poder salir correctamente. Se nota mucho a su nacimiento cuando su cabeza tiene una forma un poquito divertida o durante la lactancia , cuando siempre tiene un lado preferido para chupar. Todo estos esfuerzos le puede dar disfunciones en su sistema nervioso.<br><br>Desde su nacimiento y durante todo su desarollo , el bebe tiene que pasar por diferentes etapas , siguiendo un orden.<br><br><ul>Estas etapas son sinonimos de un buen desarollo sensorial y motor: <li>El desarollo motor le permitira a tener musculatura apropriada y una coordinacion de su cuerpo</li><li>El desarollo sensorial le permitira tener todos sus sentidos desarollados ( vision, olfaccion , tacto,)</li></ul><br><br>Un sistema nervioso que funciona a 100% le ayudara a pasar por todas estas etapas : mejorando su coordinacion , su equilibrio y todos los sentidos de su cuerpo.",
      "kids": "Durante todo el largo de su nacimiento, el bebe pasara por momentos muy estresantes ; de su bajada en el canal vaginal de su madre a su salida entera en un entorno externo extraño.<br><br>A lo largo de su bajada, puede ser que el bebe se queda bloqueada en una posicion o que enceuntra obstaculos que le impide esfuerzos para poder salir correctamente. Se nota mucho a su nacimiento cuando su cabeza tiene una forma un poquito divertida o durante la lactancia , cuando siempre tiene un lado preferido para chupar. Todo estos esfuerzos le puede dar disfunciones en su sistema nervioso.<br><br>Desde su nacimiento y durante todo su desarollo , el bebe tiene que pasar por diferentes etapas , siguiendo un orden.<br><br><ul>Estas etapas son sinonimos de un buen desarollo sensorial y motor: <li>El desarollo motor le permitira a tener musculatura apropriada y una coordinacion de su cuerpo</li><li>El desarollo sensorial le permitira tener todos sus sentidos desarollados ( vision, olfaccion , tacto,)</li></ul><br><br>Un sistema nervioso que funciona a 100% le ayudara a pasar por todas estas etapas : mejorando su coordinacion , su equilibrio y todos los sentidos de su cuerpo.",
      "elder": "Durante todo el largo de su nacimiento, el bebe pasara por momentos muy estresantes ; de su bajada en el canal vaginal de su madre a su salida entera en un entorno externo extraño.<br><br>A lo largo de su bajada, puede ser que el bebe se queda bloqueada en una posicion o que enceuntra obstaculos que le impide esfuerzos para poder salir correctamente. Se nota mucho a su nacimiento cuando su cabeza tiene una forma un poquito divertida o durante la lactancia , cuando siempre tiene un lado preferido para chupar. Todo estos esfuerzos le puede dar disfunciones en su sistema nervioso.<br><br>Desde su nacimiento y durante todo su desarollo , el bebe tiene que pasar por diferentes etapas , siguiendo un orden.<br><br><ul>Estas etapas son sinonimos de un buen desarollo sensorial y motor: <li>El desarollo motor le permitira a tener musculatura apropriada y una coordinacion de su cuerpo</li><li>El desarollo sensorial le permitira tener todos sus sentidos desarollados ( vision, olfaccion , tacto,)</li></ul><br><br>Un sistema nervioso que funciona a 100% le ayudara a pasar por todas estas etapas : mejorando su coordinacion , su equilibrio y todos los sentidos de su cuerpo.",
      "pregnant": "<h2 class='text-h6'>Pre-embarazo y embarazo</h2><ul>Antes et durante todo el embarazo , es vital preparar el cuerpo a todos los cambios que estaran generados: <li>Fisicos : el centro de gravidad cambia lo que influye en la postura , tensiones musculares </li><li>Quimicos : cambios hormonales que aumentan la laxidad de los ligamentos y de las articulaciones </li><li>Emocionales : conviertete en mama es un paso muy importante la vida que puede generar mucho estres y muchas nuevas preguntas para ti y el futuro </li></ul><br>Estos cambios pueden generar interferencias en tu sistema nervioso. EL sistema nervioso controla todos los otros sistemas del cuerpo y sobre todo los musculos, ligamentos y articulaciones de tu cuerpo como los musculos y ligamentos  del suelo pelvico y de tu espalda , la articulacion sacroiliaca, el coccyx.  La quiropractica puede que la pelvis y la columna estan bien alineadas y con rangos de movimientos suficientes para que el bebe tenga suficiente espacio y que puedas vivir tu embarazo de manera mas efectivo. Por eso , entendemos que la salud de una mujer embarazada es muy importante para ella y para el bebe.<br><br>Estamos certificado en la tecnica Webster , es una tecnica quiropractica que se centra en analisis y alineacion de la pelvis y sus ligamentos / musculos alrededor optimizando la funcion pelvica de la madre durante el embrazo y el parto para bajar las probabilidades del uso de medicaciones o de intervenciones cirugias durante el parto. <br><br><h2 class='text-h6'>Después del parto</h2>El parto es un evento muy estresante al nivel fisico ( horas de contracciones, salida del bebe) , quimico (cambios hormonales con subida de leche) i emocional ( llegada del bebe , realisacion de ser madre, depresion post-parto).La quiropractica puede ayudarte a mejorar tu recuperacion post-parto ayudando a tu cuerpo a funcionar mejor para que puedas disfrutar a 100% de este nuevo paso en tu vida.",
      "workers": "Muchos estudios sobre la quiropractica y el cerebro han demostrado la potencia de los ajustes en los cambios de la plasticidad cerebral. Mas precisamente, los ajustes quiropracticos aumentan la actividad en la parte prefrontal.<br><br><ul>La parte prefrontal esta usada por 4 aspectos: <li>la toma de decision </li><li>la cognicion que son los procesos mentales que nos permiten recibir, seleccionar, almacenar, transformar, desarrollar y recuperar información que hemos recibido de estímulos externos</li><li>el comportamiento social</li><li>la expresión de la personalidad </li></ul><br><ul>Estos 4 aspectos ayudan al rendimiento de los trabajadores mejorando: <li>la eficiencia</li><li>el tiempo de reaccion</li><li>el rendimiento social</li><li>el nivel de estres </li></ul><br><ul>Al largo plazo, la quiropractica en el mundo laboral favorece: <li>menos bajas laborales por problemas de salud tipo : depresion, lumbago, dolor de cabeza</li><li>mejor retención del personal con trabajadores que pueden manejar mejor el estres y sus otros sintomas </li><li>mejor rendimiento laboral</li></ul>",
      "sport": "Durante todo el largo de su nacimiento, el bebe pasara por momentos muy estresantes ; de su bajada en el canal vaginal de su madre a su salida entera en un entorno externo extraño.<br><br>A lo largo de su bajada, puede ser que el bebe se queda bloqueada en una posicion o que enceuntra obstaculos que le impide esfuerzos para poder salir correctamente. Se nota mucho a su nacimiento cuando su cabeza tiene una forma un poquito divertida o durante la lactancia , cuando siempre tiene un lado preferido para chupar. Todo estos esfuerzos le puede dar disfunciones en su sistema nervioso.<br><br>Desde su nacimiento y durante todo su desarollo , el bebe tiene que pasar por diferentes etapas , siguiendo un orden.<br><br><ul>Estas etapas son sinonimos de un buen desarollo sensorial y motor: <li>El desarollo motor le permitira a tener musculatura apropriada y una coordinacion de su cuerpo</li><li>El desarollo sensorial le permitira tener todos sus sentidos desarollados ( vision, olfaccion , tacto,)</li></ul><br><br>Un sistema nervioso que funciona a 100% le ayudara a pasar por todas estas etapas : mejorando su coordinacion , su equilibrio y todos los sentidos de su cuerpo."
    }
  }
}
</i18n>
